version: '3.1'
services:
  jupyter:
    container_name: jupyter
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - 127.0.0.1:8888:8888
        - 127.0.0.1:8889:8889
    volumes:
        - ~/repos/DSE:/home/admin/notebooks
